"""add_business_signal

Revision ID: 4d4cf97db75c
Revises: 7915602dc006
Create Date: 2026-10-03 17:47:07.044692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4cf97db75c'
down_revision: Union[str, Sequence[str], None] = '7915602dc006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('change_event_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('observed_change', sa.Text(), nullable=False),
    sa.Column('potential_implication', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classification_status', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['monitored_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_signals_change_event_id'), ['change_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_business_signals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_signals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_signals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_signals_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_signals_signal_type'), ['signal_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_business_signals_page_id'))
        batch_op.drop_index(batch_op.f('ix_business_signals_id'))
        batch_op.drop_index(batch_op.f('ix_business_signals_created_at'))
        batch_op.drop_index(batch_op.f('ix_business_signals_company_id'))
        batch_op.drop_index(batch_op.f('ix_business_signals_change_event_id'))

    op.drop_table('business_signals')
    # ### end Alembic commands ###
