"""initial_schema

Revision ID: 687da7b15901
Revises: 
Create Date: 2026-10-03 17:42:08.334465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687da7b15901'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    op.create_table('monitored_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('page_type', sa.String(length=50), nullable=False),
    sa.Column('crawl_interval_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_crawl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_pages_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitored_pages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitored_pages_next_crawl_at'), ['next_crawl_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitored_pages_url'), ['url'], unique=False)

    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['monitored_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_runs_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_runs_status'), ['status'], unique=False)
        batch_op.create_index('uq_active_crawl_per_page', ['page_id'], unique=True, sqlite_where=sa.text("status IN ('queued', 'running')"))

    op.create_table('page_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('crawl_run_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_path', sa.String(length=1024), nullable=False),
    sa.Column('html_path', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['monitored_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_snapshots_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_snapshots_crawl_run_id'), ['crawl_run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_page_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_snapshots_page_id'), ['page_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_snapshots_page_id'))
        batch_op.drop_index(batch_op.f('ix_page_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_page_snapshots_crawl_run_id'))
        batch_op.drop_index(batch_op.f('ix_page_snapshots_content_hash'))
        batch_op.drop_index(batch_op.f('ix_page_snapshots_captured_at'))

    op.drop_table('page_snapshots')
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.drop_index('uq_active_crawl_per_page', sqlite_where=sa.text("status IN ('queued', 'running')"))
        batch_op.drop_index(batch_op.f('ix_crawl_runs_status'))
        batch_op.drop_index(batch_op.f('ix_crawl_runs_page_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_runs_id'))

    op.drop_table('crawl_runs')
    with op.batch_alter_table('monitored_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_pages_url'))
        batch_op.drop_index(batch_op.f('ix_monitored_pages_next_crawl_at'))
        batch_op.drop_index(batch_op.f('ix_monitored_pages_id'))
        batch_op.drop_index(batch_op.f('ix_monitored_pages_company_id'))

    op.drop_table('monitored_pages')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_id'))
        batch_op.drop_index(batch_op.f('ix_companies_domain'))

    op.drop_table('companies')
    # ### end Alembic commands ###
