"""add_change_event

Revision ID: 7915602dc006
Revises: 687da7b15901
Create Date: 2026-10-03 17:44:06.376916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7915602dc006'
down_revision: Union[str, Sequence[str], None] = '687da7b15901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('previous_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('current_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('diff_path', sa.String(length=1024), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_meaningful', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['page_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['monitored_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['page_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('previous_snapshot_id', 'current_snapshot_id', name='uq_change_event_snapshots')
    )
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_events_current_snapshot_id'), ['current_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_previous_snapshot_id'), ['previous_snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_events_previous_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_change_events_page_id'))
        batch_op.drop_index(batch_op.f('ix_change_events_id'))
        batch_op.drop_index(batch_op.f('ix_change_events_detected_at'))
        batch_op.drop_index(batch_op.f('ix_change_events_current_snapshot_id'))

    op.drop_table('change_events')
    # ### end Alembic commands ###
